stages:
  - test

default:
  image: alpine

test_a:
  stage: test
  tags:
    - ansible
  script:
    - echo ${CI_PROJECT_DIR}/inventory.yml
    - ansible-playbook -i "${CI_PROJECT_DIR}"/inventory.yml "${CI_PROJECT_DIR}"/playbook-a.yml
